set_group("basic")

add_target("getinfo.c")
add_target("rect.c")
add_target("rotate.c")
add_target("house.c")
add_target("fivecircle.c")
add_target("point.c")
add_target("opengl.c")
add_target("center.c")
add_target("keyrotate.c")