name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        brew install xmake
        brew install gl2ps
    - name: build
      run: |
        xmake build -y
