name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      shell: pwsh
      run: |
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop install xmake
    - name: build
      run: |
        ~\scoop\shims\xmake build -y
