name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      shell: pwsh
      run: |
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop install xmake
    - name: build
      env: 
        VCPKG_ROOT: ${{ env.VCPKG_INSTALLATION_ROOT }}
      run: |
        xmake build -y
