name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: build
      run: |
        xmake build -y
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-artifact
        path: build/windows
        retention-days: 2
